### ISSUE TITLE
分类问题

### ISSUE THREAD

**Issue by anonymously123456** [Jack-Cherish/Deep-Learning#10]
你好，该代码能进行多分类吗（比如4分类）？麻烦博主可以指导一下吗？直接修改n_classes=4报错了，期待你的回复

![image](https://user-images.githubusercontent.com/56376393/100959725-d9f4e980-3559-11eb-8372-bec85f8b74fb.png)

**Comment by Jack-Cherish** [comment]
数据和你设置的class没有对应上。
