### ISSUE TITLE
loss存在问题

### ISSUE THREAD

**Issue by LouZhiX** [Jack-Cherish/Deep-Learning#2]
为什么在最后的分类函数中使用sigmoid函数分类，这个不是用来做二分类的吗？应该是使用softmax函数吧，而且修改为softmax函数之后再运行会发现loss会一直上升，所以我不知道问题出现在哪儿了？

**Comment by Jack-Cherish** [comment]
@LouZhiX 用softmax也可以的，不过需要自己改下函数。
