### ISSUE TITLE
看一下你的博客，电脑烫到飞起，用我电脑挖矿请说一声谢谢

### ISSUE THREAD

**Issue by richard1225** [Jack-Cherish/Deep-Learning#3]
看一下你的博客，电脑烫到飞起，chrome瞬间cpu占用40% ， 关掉之后就调到0了，
用大家的电脑挖矿请提前说一声谢谢

**Comment by Jack-Cherish** [comment]
@richard1225 从哪里得来的这个结论？我从来没有部署过这些东西。你这说的有点莫名其妙，找到代码段再捶，谢谢。
