### ISSUE TITLE
博主这是转载？

### ISSUE THREAD

**Issue by howie6879** [Jack-Cherish/Deep-Learning#4]
看文章转载可以，但为什么直接github上显示是自己的教程并且代码也基本一样？

https://github.com/Jack-Cherish/Deep-Learning

**Comment by Jack-Cherish** [comment]
@howie6879 你在说什么？哪个请指明。

**Comment by howie6879** [comment]
哈哈 我大惊小怪了

**Comment by Jack-Cherish** [comment]
@howie6879 哦，看到了，你说的是这个啊https://github.com/hanbt/learn_dl/issues/40
转载的第一天我就已经说明了：https://github.com/Jack-Cherish/Deep-Learning/tree/master/Tutorial
那边的issues也请说明下，不想被冤枉啊。

**Comment by howie6879** [comment]
嗯嗯 抱歉 我的问题 但是我也是本着开源共享精神

**Comment by Jack-Cherish** [comment]
@howie6879 理解理解，哈哈。
