### ISSUE TITLE
我用深度学习训练了一些英数验证码

### ISSUE THREAD

**Issue by mengpengfei** [Jack-Cherish/Deep-Learning#6]
请问下，我用深度学习训练了一些英数验证码，然后得到一个模型，过了一段时间之后，我又有了新得风格的样本，可以在原来的模型上继续训练吗，如果在原来的模型使用新的样本继续训练的话， 最后得到的模型，还能识别以前的那些风格的验证码
如果 50万张样本，100多种类型的验证码，能不能训练出来一个通用的模型出来

**Comment by Jack-Cherish** [comment]
@mengpengfei 可以的，扩充数据集，或者对图像预处理，变成相同风格的验证码。
