### ISSUE TITLE
我想指定我应该使用哪个版本的TensorFlow

### ISSUE THREAD

**Issue by DrakenZeng** [Jack-Cherish/Deep-Learning#7]
运行环境 windows10 python 3.7.2
cpu g4400

**Comment by Jack-Cherish** [comment]
你的意思是，你有好几个版本的tf，想指定用一个版本？那你可以配置环境变量。

**Comment by DrakenZeng** [comment]
我的意思是 我使用最新的 1.13.1出现预加载错误

**Comment by Jack-Cherish** [comment]
@Darkells 这个原因很多，没错误信息，我也不清楚你这是什么情况。
