### ISSUE TITLE
您好，请问可以把垃圾分类项目的数据集转化成txt文件开源吗，小白实在不会做

### ISSUE THREAD

**Issue by ghost** [Jack-Cherish/Deep-Learning#8]
谢谢作者大大！！

**Comment by SerenaDDeng** [comment]
那个啥 我不是作者啊 你是不是发错啦



发自我的iPhone


------------------ 原始邮件 ------------------

**Comment by chenbaibing** [comment]
不好意思啊，我不是作者，你可能发错人了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jack-Cherish/Deep-Learning"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月9日(星期一) 中午11:15
收件人:&nbsp;"Jack-Cherish/Deep-Learning"<Deep-Learning@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Jack-Cherish/Deep-Learning] 您好，请问可以把垃圾分类项目的数据集转化成txt文件开源吗，小白实在不会做 (#8)





 
谢谢作者大大！！

**Comment by Jack-Cherish** [comment]
@SerenaDDeng @chenbaibing 所有watch项目的人都会收到邮件的~
@a6518413 这个已经没了，不难的，就是读取图片的路径，然后写个标签。
