### ISSUE TITLE
TypeError: object.__new__() takes exactly one argument (the type to instantiate)

### ISSUE THREAD

**Issue by LimitedLi** [Jack-Cherish/Deep-Learning#9]
您好，感谢您的分享。我在运行代码时遇到了以下问题，在网上没有找到解决办法，可以帮我看一下该如何解决吗？
Traceback (most recent call last):
  File "F:/pythonProject/Unet/Lib/dataset.py", line 44, in <module>
    isbi_dataset = ISBI_Loader("C:/Users/Administrator/Desktop/Segmentation/Unet/data/data/train/")
  File "F:\Anaconda3\lib\typing.py", line 875, in __new__
    obj = super().__new__(cls, *args, **kwds)
TypeError: object.__new__() takes exactly one argument (the type to instantiate)

**Comment by Jack-Cherish** [comment]
@TinyMonsterLee 检查数据路径等，我测试是没有这种情况。
